on:
  push:
  pull_request:
  schedule:
    - cron: '*/10 * * * *'

jobs:
#  docker_job:
#    runs-on: ubuntu-latest
#    name: A job to say hello
#    steps:
#    - name: Hello world action step
#      id: hello
#      uses: actions/hello-world-docker-action@v1
#      with:
#        who-to-greet: 'P1P1P1P1P1Mona the Octocat'
#    # Use the output from the `hello` step
#    - name: Get the output time
#      run: echo "The time was ${{ steps.hello.outputs.time }}"

  makefile_job:
    runs-on: ubuntu-latest
    name: checkout fetch eval update add commit loop
    steps:
    - name: checkout
      id: fiirst
      uses: actions/checkout@v2
    - name: make test
      id: make_test
      run: make test
    - name: make update_tld_file
      id: make_update_tld_file
      run: make update_tld_file
    - name: make filter_tld_file
      id: make_filter_tld_file
      run: make filter_tld_file
    - name: make censore_tld_file
      id: make_censore_tld_file
      run: make censore_tld_file
   # skipp eval, update
    - name: Commit files
      run: |
        git config --local user.email "action@github.bot"
        git config --local user.name "zrthstr"
        git commit -m "update data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
