on:
  schedule:
    - cron: '55 0 * * 4'

jobs:
  makefile_job:
    runs-on: ubuntu-latest
    name: checkout fetch eval update add commit loop
    steps:
    - name: checkout
      id: first
      uses: actions/checkout@v2
    - name: make update_tld_file
      id: make_update_tld_file
      run: make update_tld_file
    - name: make filter_tld_file
      id: make_filter_tld_file
      run: make filter_tld_file
    - name: make censore_tld_file
      id: make_censore_tld_file
      run: make censore_tld_file
    - name: make count_sane_tld_file
      id: make_count_sane_tld_file
      run: make count_sane_tld_file
    - name: make install_py_dep
      id: make_install_py_dep
      run: make install_py_dep
    - name: make clean_ns
      id: make_clean_ns
      run: make clean_ns
    - name: make get_ns
      id: make_get_ns
      run: make get_ns

   # skipp eval, update
    - name: Commit files
      run: |
        git config --local user.email "action@github.bot"
        git config --local user.name "zrthstr"
        git commit -m "update ns" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
