on:
  push:
  schedule:
    - cron: '55 0 * * 5'

#push:
#pull_request:

jobs:
  makefile_job:
    runs-on: ubuntu-latest
    name: checkout fetch eval update add commit loop
    steps:
    - name: checkout
      id: first
      uses: actions/checkout@v2
    - name: make install_py_dep
      id: make_install_py_dep
      run: make install_py_dep
    - name: make clean_zone
      id: make_clean_zone
      run: make clean_zone
    - name: Push changes1
      run: echo ${{ secrets.PAT }} | wc
      with:
        github_token: ${{ secrets.PAT }}
    - name: make get_zone
      id: make_get_zone
      run: make get_zone
    - name: Push changes2
      run: echo ${{ secrets.PAT }} | wc
      with:
        github_token: ${{ secrets.PAT }}

    - name: Commit files
      run: |
        git config --local user.email "action@github.bot"
        git config --local user.name "zrthstr"
        git commit -m "update zones" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
